### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/flatpak_flutter#2]
Depending on the install apps, one may see this
```
[19:21:11.916724] [D] [flutter] [System Installation]
[19:21:11.916789] [D] [flutter] id: default
[19:21:11.916819] [D] [flutter] display_name: Default system installation
[19:21:11.916847] [D] [flutter] path: /var/lib/flatpak
[19:21:11.916894] [D] [flutter] noInteraction: false
[19:21:11.916922] [D] [flutter] isUser: false
[19:21:11.916949] [D] [flutter] priority: 0
[19:21:11.916983] [D] [flutter] language: en
[19:21:11.917014] [D] [flutter] locale: en
[19:21:11.917043] [D] [flutter] Remote Count: 1
[19:21:11.917774] [D] [flutter] 	[Remote]
[19:21:11.917818] [D] [flutter] 	name: flathub
[19:21:11.917849] [D] [flutter] 	url: https://dl.flathub.org/repo/
[19:21:11.917887] [D] [flutter] 	title: Flathub
[19:21:11.917914] [D] [flutter] 	comment: Central repository of Flatpak applications
[19:21:11.917943] [D] [flutter] 	description: Central repository of Flatpak applications
[19:21:11.917970] [D] [flutter] 	homepage: https://flathub.org/
[19:21:11.917997] [D] [flutter] 	icon: https://dl.flathub.org/repo/logo.svg
[19:21:11.918042] [D] [flutter] 	remoteType: Static
[19:21:11.923593] [D] [flutter] 	appstreamTimestamp: 2024-11-06 00:34:29.000Z
[19:21:11.923639] [D] [flutter] 	appstreamDir: /var/lib/flatpak/appstream/flathub/x86_64/active
[19:21:11.923668] [D] [flutter] 	gpgVerify: true
[19:21:11.923694] [D] [flutter] 	noEnumerate: false
[19:21:11.923719] [D] [flutter] 	noDeps: false
[19:21:11.923744] [D] [flutter] 	disabled: false
[19:21:11.923769] [D] [flutter] 	prio: 1
[19:21:11.924229] [D] [flutter] [User Installation]
[19:21:11.924251] [D] [flutter] id: user
[19:21:11.924268] [D] [flutter] display_name: User installation
[19:21:11.924281] [D] [flutter] path: /home/tcna/.local/share/flatpak
[19:21:11.924294] [D] [flutter] noInteraction: false
[19:21:11.924306] [D] [flutter] isUser: true
[19:21:11.924319] [D] [flutter] priority: 0
[19:21:11.924333] [D] [flutter] language: en
[19:21:11.924346] [D] [flutter] locale: en
[19:21:11.924359] [D] [flutter] Remote Count: 0
[19:21:11.927515] [E] [FlatpakPlugin] Failed to open file “/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.Debug.default/x86_64/23.08/46fcecf60f75b0d83929db26811e19bb05792a8ff429a1abed1c2b75d9ab21a6/files/share/app-info/xmls/org.freedesktop.Platform.GL.Debug.default.xml.gz”: No such file or directory
[19:21:11.927537] [E] [FlatpakPlugin] Failed to open file “/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.Debug.default/x86_64/23.08-extra/cbb6f122d7a106b492f42784ea8089e10ad7574ccdd737bce8125664a129c97b/files/share/app-info/xmls/org.freedesktop.Platform.GL.Debug.default.xml.gz”: No such file or directory
[19:21:11.927579] [E] [FlatpakPlugin] Failed to open file “/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.Debug.default/x86_64/24.08/9286c363aeceb2e12217af2a0e4b67da6cb9c0bda8cd693eb9b050e60b297701/files/share/app-info/xmls/org.freedesktop.Platform.GL.Debug.default.xml.gz”: No such file or directory
[19:21:11.927592] [E] [FlatpakPlugin] Failed to open file “/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.Debug.default/x86_64/24.08extra/d46edb3855ba6e459c8496ae3121f0fa492a803a705430c95fb7ef0a89ce3acf/files/share/app-info/xmls/org.freedesktop.Platform.GL.Debug.default.xml.gz”: No such file or directory
[19:21:11.927972] [E] [FlatpakPlugin] Failed to open file “/var/lib/flatpak/runtime/org.freedesktop.Platform.Locale/x86_64/24.08/07ce90ba9f37df9e87ee3715d588dd6ddc4bc764b68723156f1e3d90acc2297a-en/files/share/app-info/xmls/org.freedesktop.Platform.Locale.xml.gz”: No such file or directory
[19:21:11.933884] [D] [flutter] [Application]
[19:21:11.933956] [D] [flutter] name: Discord Inc.
[19:21:11.933986] [D] [flutter] id: default
[19:21:11.934012] [D] [flutter] summary: Messaging, voice and video client
[19:21:11.934050] [D] [flutter] version: 0.0.73
[19:21:11.934079] [D] [flutter] origin: flathub
[19:21:11.934106] [D] [flutter] license: LicenseRef-proprietary
[19:21:11.934284] [D] [flutter] installed_size: 266.75 MiB
[19:21:11.934329] [D] [flutter] deploy_dir: /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/2d65c8d3af90177a7dcd00fe9f507b34d255443ebef50885f5078a51703f9015
[19:21:11.934366] [D] [flutter] is_current: true
[19:21:11.934392] [D] [flutter] content_rating_type: oars-1.1
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      ListBase.firstWhere (dart:collection/list.dart:132:5)
#1      new ContentRatingOarsOneDotOne.fromJson (package:flatpak_flutter/src/oars_rating.dart:174:44)
#2      _MyHomePageState._incrementCounter (package:flatpak_flutter/main.dart:226:54)
<asynchronous suspension>
```

**Comment by jwinarske** [comment]
resolved with https://github.com/meta-flutter/flatpak_flutter/issues/2
